# Supabase 專案配置檔
# 本檔案用於本地開發環境設定

[project]
# 在 Supabase Dashboard 取得你的 Project ID
# project_id = "your-project-id"

[api]
# API 設定
enabled = true
port = 54321
max_rows = 1000

[db]
# 資料庫設定
port = 54322

[studio]
# Supabase Studio 設定
enabled = true
port = 54323

[auth]
# 認證設定
enabled = true
site_url = "oflow://auth/callback"

[storage]
# 儲存設定（未來用於上傳商品圖片等）
enabled = true

