// OFlow 假資料

import type {
  AnalyticsData,
  CatalogItem,
  Customer,
  DashboardStats,
  Order,
  RevenueData,
  TodoItem,
  TopProduct,
} from "./types";

// 組織資料
export const mockOrganization = {
  id: "org_1",
  name: "甜蜜時光烘焙坊",
  businessType: "bakery",
  createdAt: new Date("2024-01-15"),
};

// 顧客資料
export const mockCustomers: Customer[] = [
  {
    id: "cust_1",
    orgId: "org_1",
    name: "王小明",
    phone: "0912-345-678",
    tags: ["VIP", "returning"],
    lastSeenAt: new Date("2025-10-17T10:30:00"),
    totalOrders: 15,
    totalSpent: 12500,
  },
  {
    id: "cust_2",
    orgId: "org_1",
    name: "李美華",
    phone: "0923-456-789",
    tags: ["returning"],
    lastSeenAt: new Date("2025-10-16T14:20:00"),
    totalOrders: 8,
    totalSpent: 6800,
  },
  {
    id: "cust_3",
    orgId: "org_1",
    name: "張大維",
    phone: "0934-567-890",
    tags: ["new"],
    lastSeenAt: new Date("2025-10-17T09:15:00"),
    totalOrders: 1,
    totalSpent: 500,
  },
  {
    id: "cust_4",
    orgId: "org_1",
    name: "陳雅婷",
    phone: "0945-678-901",
    tags: ["VIP", "frequent"],
    lastSeenAt: new Date("2025-10-15T16:45:00"),
    totalOrders: 23,
    totalSpent: 18900,
  },
  {
    id: "cust_5",
    orgId: "org_1",
    name: "林志豪",
    phone: "0956-789-012",
    tags: ["returning"],
    lastSeenAt: new Date("2025-10-14T11:30:00"),
    totalOrders: 5,
    totalSpent: 4200,
  },
  {
    id: "cust_6",
    orgId: "org_1",
    name: "黃淑芬",
    phone: "0967-890-123",
    tags: ["new"],
    lastSeenAt: new Date("2025-10-17T13:20:00"),
    totalOrders: 1,
    totalSpent: 800,
  },
  {
    id: "cust_7",
    orgId: "org_1",
    name: "吳建國",
    phone: "0978-901-234",
    tags: ["returning"],
    lastSeenAt: new Date("2025-10-13T10:00:00"),
    totalOrders: 6,
    totalSpent: 5100,
  },
  {
    id: "cust_8",
    orgId: "org_1",
    name: "周美玲",
    phone: "0989-012-345",
    tags: ["VIP", "returning"],
    lastSeenAt: new Date("2025-10-16T15:30:00"),
    totalOrders: 18,
    totalSpent: 14500,
  },
  {
    id: "cust_9",
    orgId: "org_1",
    name: "鄭子軒",
    phone: "0912-234-567",
    tags: ["frequent"],
    lastSeenAt: new Date("2025-10-17T08:45:00"),
    totalOrders: 12,
    totalSpent: 9800,
  },
  {
    id: "cust_10",
    orgId: "org_1",
    name: "劉怡君",
    phone: "0923-345-678",
    tags: ["returning"],
    lastSeenAt: new Date("2025-10-12T14:00:00"),
    totalOrders: 7,
    totalSpent: 5900,
  },
];

// 商品資料
export const mockCatalogItems: CatalogItem[] = [
  {
    id: "item_1",
    orgId: "org_1",
    type: "product",
    name: "原味巴斯克蛋糕",
    price: 450,
    active: true,
    description: "經典原味，濃郁滑順",
    options: { flavors: ["原味"], temperature: ["冷藏"] },
  },
  {
    id: "item_2",
    orgId: "org_1",
    type: "product",
    name: "抹茶巴斯克蛋糕",
    price: 480,
    active: true,
    description: "日本宇治抹茶，微苦回甘",
    options: { flavors: ["抹茶"], temperature: ["冷藏"] },
  },
  {
    id: "item_3",
    orgId: "org_1",
    type: "product",
    name: "巧克力布朗尼",
    price: 350,
    active: true,
    description: "濃郁巧克力，口感紮實",
    options: { temperature: ["常溫", "冷藏"] },
  },
  {
    id: "item_4",
    orgId: "org_1",
    type: "product",
    name: "檸檬塔",
    price: 120,
    active: true,
    description: "酸甜清爽，夏日首選",
  },
  {
    id: "item_5",
    orgId: "org_1",
    type: "product",
    name: "草莓生乳捲",
    price: 380,
    active: true,
    description: "季節限定，新鮮草莓",
    options: { temperature: ["冷藏"] },
  },
  {
    id: "item_6",
    orgId: "org_1",
    type: "product",
    name: "法式馬卡龍（6入）",
    price: 280,
    active: true,
    description: "六種口味，精緻禮盒",
    options: { flavors: ["綜合"] },
  },
  {
    id: "item_7",
    orgId: "org_1",
    type: "product",
    name: "提拉米蘇",
    price: 420,
    active: true,
    description: "義式經典，咖啡香濃",
    options: { temperature: ["冷藏"] },
  },
  {
    id: "item_8",
    orgId: "org_1",
    type: "product",
    name: "芋泥千層",
    price: 500,
    active: true,
    description: "手工芋泥，層層堆疊",
    options: { temperature: ["冷藏"] },
  },
  {
    id: "item_9",
    orgId: "org_1",
    type: "product",
    name: "焦糖瑪德蓮（10入）",
    price: 200,
    active: false,
    description: "暫時缺貨",
  },
  {
    id: "item_10",
    orgId: "org_1",
    type: "product",
    name: "肉桂捲",
    price: 90,
    active: true,
    description: "現烤溫熱，肉桂香氣",
  },
];

// 訂單資料
export const mockOrders: Order[] = [
  {
    id: "order_1",
    orgId: "org_1",
    customerId: "cust_1",
    type: "order",
    total: 900,
    status: "pending",
    deliveryMethod: "pickup",
    notes: "分兩次取貨：週五拿一顆，週日拿一顆",
    createdAt: new Date("2025-10-17T10:30:00"),
    items: [
      {
        id: "oi_1",
        orderId: "order_1",
        catalogItemId: "item_1",
        name: "原味巴斯克蛋糕",
        quantity: 2,
        unitPrice: 450,
      },
    ],
    suborders: [
      {
        id: "sub_1",
        orderId: "order_1",
        scheduleAt: new Date("2025-10-18T15:00:00"),
        quantity: 1,
        status: "scheduled",
        notes: "第一次取貨",
      },
      {
        id: "sub_2",
        orderId: "order_1",
        scheduleAt: new Date("2025-10-20T10:00:00"),
        quantity: 1,
        status: "scheduled",
        notes: "第二次取貨",
      },
    ],
  },
  {
    id: "order_2",
    orgId: "org_1",
    customerId: "cust_2",
    type: "order",
    total: 830,
    status: "paid",
    deliveryMethod: "pickup",
    createdAt: new Date("2025-10-16T14:20:00"),
    items: [
      {
        id: "oi_2",
        orderId: "order_2",
        catalogItemId: "item_2",
        name: "抹茶巴斯克蛋糕",
        quantity: 1,
        unitPrice: 480,
      },
      {
        id: "oi_3",
        orderId: "order_2",
        catalogItemId: "item_3",
        name: "巧克力布朗尼",
        quantity: 1,
        unitPrice: 350,
      },
    ],
    payment: {
      id: "pay_2",
      orderId: "order_2",
      method: "transfer",
      amount: 830,
      status: "confirmed",
      confirmedAt: new Date("2025-10-16T14:25:00"),
    },
  },
  {
    id: "order_3",
    orgId: "org_1",
    customerId: "cust_3",
    type: "order",
    total: 500,
    status: "paid",
    deliveryMethod: "delivery",
    notes: "請在下午3點後送達",
    createdAt: new Date("2025-10-17T09:15:00"),
    items: [
      {
        id: "oi_4",
        orderId: "order_3",
        catalogItemId: "item_5",
        name: "草莓生乳捲",
        quantity: 1,
        unitPrice: 380,
      },
      {
        id: "oi_5",
        orderId: "order_3",
        catalogItemId: "item_4",
        name: "檸檬塔",
        quantity: 1,
        unitPrice: 120,
      },
    ],
    payment: {
      id: "pay_3",
      orderId: "order_3",
      method: "transfer",
      amount: 500,
      status: "confirmed",
      confirmedAt: new Date("2025-10-17T09:20:00"),
    },
  },
  {
    id: "order_4",
    orgId: "org_1",
    customerId: "cust_4",
    type: "order",
    total: 1200,
    status: "shipped",
    deliveryMethod: "pickup",
    notes: "週二、週四各取一次",
    createdAt: new Date("2025-10-15T16:45:00"),
    items: [
      {
        id: "oi_6",
        orderId: "order_4",
        catalogItemId: "item_7",
        name: "提拉米蘇",
        quantity: 2,
        unitPrice: 420,
      },
      {
        id: "oi_7",
        orderId: "order_4",
        catalogItemId: "item_6",
        name: "法式馬卡龍（6入）",
        quantity: 1,
        unitPrice: 280,
      },
      {
        id: "oi_8",
        orderId: "order_4",
        catalogItemId: "item_10",
        name: "肉桂捲",
        quantity: 1,
        unitPrice: 90,
      },
    ],
    suborders: [
      {
        id: "sub_3",
        orderId: "order_4",
        scheduleAt: new Date("2025-10-15T14:00:00"),
        status: "completed",
        notes: "已於 10/15 取貨",
      },
      {
        id: "sub_4",
        orderId: "order_4",
        scheduleAt: new Date("2025-10-17T14:00:00"),
        status: "scheduled",
        notes: "待取貨",
      },
    ],
  },
  {
    id: "order_5",
    orgId: "org_1",
    customerId: "cust_5",
    type: "order",
    total: 760,
    status: "completed",
    deliveryMethod: "pickup",
    createdAt: new Date("2025-10-14T11:30:00"),
    items: [
      {
        id: "oi_9",
        orderId: "order_5",
        catalogItemId: "item_8",
        name: "芋泥千層",
        quantity: 1,
        unitPrice: 500,
      },
      {
        id: "oi_10",
        orderId: "order_5",
        catalogItemId: "item_10",
        name: "肉桂捲",
        quantity: 3,
        unitPrice: 90,
      },
    ],
  },
  {
    id: "order_6",
    orgId: "org_1",
    customerId: "cust_6",
    type: "order",
    total: 800,
    status: "paid",
    deliveryMethod: "pickup",
    notes: "生日蛋糕，需要蠟燭",
    createdAt: new Date("2025-10-17T13:20:00"),
    items: [
      {
        id: "oi_11",
        orderId: "order_6",
        catalogItemId: "item_1",
        name: "原味巴斯克蛋糕",
        quantity: 1,
        unitPrice: 450,
      },
      {
        id: "oi_12",
        orderId: "order_6",
        catalogItemId: "item_3",
        name: "巧克力布朗尼",
        quantity: 1,
        unitPrice: 350,
      },
    ],
    payment: {
      id: "pay_6",
      orderId: "order_6",
      method: "transfer",
      amount: 800,
      status: "confirmed",
      confirmedAt: new Date("2025-10-17T13:25:00"),
    },
  },
  {
    id: "order_7",
    orgId: "org_1",
    customerId: "cust_7",
    type: "order",
    total: 960,
    status: "completed",
    deliveryMethod: "pickup",
    createdAt: new Date("2025-10-13T10:00:00"),
    items: [
      {
        id: "oi_13",
        orderId: "order_7",
        catalogItemId: "item_2",
        name: "抹茶巴斯克蛋糕",
        quantity: 2,
        unitPrice: 480,
      },
    ],
  },
  {
    id: "order_8",
    orgId: "org_1",
    customerId: "cust_8",
    type: "order",
    total: 1380,
    status: "paid",
    deliveryMethod: "delivery",
    notes: "公司地址：信義區松仁路100號",
    createdAt: new Date("2025-10-16T15:30:00"),
    items: [
      {
        id: "oi_14",
        orderId: "order_8",
        catalogItemId: "item_8",
        name: "芋泥千層",
        quantity: 2,
        unitPrice: 500,
      },
      {
        id: "oi_15",
        orderId: "order_8",
        catalogItemId: "item_5",
        name: "草莓生乳捲",
        quantity: 1,
        unitPrice: 380,
      },
    ],
    payment: {
      id: "pay_8",
      orderId: "order_8",
      method: "transfer",
      amount: 1380,
      status: "confirmed",
      confirmedAt: new Date("2025-10-16T15:35:00"),
    },
  },
  {
    id: "order_9",
    orgId: "org_1",
    customerId: "cust_9",
    type: "order",
    total: 660,
    status: "pending",
    deliveryMethod: "pickup",
    createdAt: new Date("2025-10-17T08:45:00"),
    items: [
      {
        id: "oi_16",
        orderId: "order_9",
        catalogItemId: "item_6",
        name: "法式馬卡龍（6入）",
        quantity: 2,
        unitPrice: 280,
      },
      {
        id: "oi_17",
        orderId: "order_9",
        catalogItemId: "item_10",
        name: "肉桂捲",
        quantity: 1,
        unitPrice: 90,
      },
    ],
  },
  {
    id: "order_10",
    orgId: "org_1",
    customerId: "cust_10",
    type: "order",
    total: 1050,
    status: "completed",
    deliveryMethod: "pickup",
    createdAt: new Date("2025-10-12T14:00:00"),
    items: [
      {
        id: "oi_18",
        orderId: "order_10",
        catalogItemId: "item_7",
        name: "提拉米蘇",
        quantity: 1,
        unitPrice: 420,
      },
      {
        id: "oi_19",
        orderId: "order_10",
        catalogItemId: "item_1",
        name: "原味巴斯克蛋糕",
        quantity: 1,
        unitPrice: 450,
      },
      {
        id: "oi_20",
        orderId: "order_10",
        catalogItemId: "item_10",
        name: "肉桂捲",
        quantity: 2,
        unitPrice: 90,
      },
    ],
  },
];

// 將顧客資料加入訂單
mockOrders.forEach((order) => {
  order.customer = mockCustomers.find((c) => c.id === order.customerId);
});

// Dashboard 統計資料
export const mockDashboardStats: DashboardStats = {
  todayRevenue: 3460,
  todayOrders: 5,
  pendingOrders: 2,
  weeklyReturnRate: 68,
  revenueChange: 12.5,
  ordersChange: 8.3,
};

// 營收趨勢資料（7天）
export const mockRevenueData: RevenueData[] = [
  { date: "10/11", revenue: 3200 },
  { date: "10/12", revenue: 2800 },
  { date: "10/13", revenue: 4100 },
  { date: "10/14", revenue: 3600 },
  { date: "10/15", revenue: 4500 },
  { date: "10/16", revenue: 3900 },
  { date: "10/17", revenue: 3460 },
];

// 今日待辦事項
export const mockTodoItems: TodoItem[] = [
  {
    id: "todo_1",
    title: "王小明的訂單待確認付款",
    type: "order",
    orderId: "order_1",
    completed: false,
    time: "10:30",
  },
  {
    id: "todo_2",
    title: "提醒周美玲今日取貨",
    type: "reminder",
    orderId: "order_8",
    completed: false,
    time: "14:00",
  },
  {
    id: "todo_3",
    title: "鄭子軒的訂單待確認付款",
    type: "order",
    orderId: "order_9",
    completed: false,
    time: "08:45",
  },
  {
    id: "todo_4",
    title: "檢查冷藏庫存",
    type: "alert",
    completed: false,
  },
  {
    id: "todo_5",
    title: "準備明日出貨訂單",
    type: "reminder",
    completed: false,
  },
];

// 熱銷商品 Top 5
export const mockTopProducts: TopProduct[] = [
  { name: "原味巴斯克蛋糕", sales: 24, revenue: 10800 },
  { name: "抹茶巴斯克蛋糕", sales: 18, revenue: 8640 },
  { name: "芋泥千層", sales: 15, revenue: 7500 },
  { name: "提拉米蘇", sales: 12, revenue: 5040 },
  { name: "草莓生乳捲", sales: 10, revenue: 3800 },
];

// 分析資料
export const mockAnalyticsData: AnalyticsData = {
  revenue: mockRevenueData,
  topProducts: mockTopProducts,
  customerStats: {
    new: 2,
    returning: 6,
    vip: 3,
  },
};
